/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./erc20.sol";
export type { erc20Sol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { ERC20 } from "./erc20.sol/ERC20";
export { ERC20__factory } from "./factories/erc20.sol/ERC20__factory";
export { Lock__factory } from "./factories/Lock__factory";
